version: "3.8"

services:
  docs-calidad:
    build: .
    container_name: docs-calidad
    ports:
      - "0777:3001"
    volumes:
      - ./estructura.json:/app/estructura.json
    restart: unless-stopped

